### ISSUE TITLE
语言支持

### ISSUE THREAD

**Issue by AnnoyedDev** [Hqndler/Yolobatch#1]
我很高兴看到你的项目已经上线了，但是安装过程中似乎出现了一些问题。实际上，说明文件写得非常不清楚。请重新编写说明文件，并包括大多数人使用的语言。
再次感谢你的回复，我希望答案是积极的。这件事情对于你、我或其他人来说都很重要。

**Comment by Hqndler** [comment]
https://letmegooglethat.com/?q=how+to+learn+english

**Comment by MagikarpLaCarpe** [comment]
i will bomb your country i'm a friend of xi jinping

**Comment by AnnoyedDev** [comment]
Thanks now i can speak english, i will not bother you again, have a good day sir
